samples: config/snp_data.csv

ref :
  species: homo_sapiens

  data_type: snp

  build: hg19

  contig_lenght: [ 
          "##contig=<ID=chr1,length=249250621,assembly=hg19>",
            "##contig=<ID=chr2,length=243199373,assembly=hg19>",
            "##contig=<ID=chr3,length=198022430,assembly=hg19>",
            "##contig=<ID=chr4,length=191154276,assembly=hg19>",
            "##contig=<ID=chr5,length=180915260,assembly=hg19>",
            "##contig=<ID=chr6,length=171115067,assembly=hg19>",
            "##contig=<ID=chr7,length=159138663,assembly=hg19>",
            "##contig=<ID=chr8,length=146364022,assembly=hg19>",
            "##contig=<ID=chr9,length=141213431,assembly=hg19>",
            "##contig=<ID=chr10,length=135534747,assembly=hg19>",
            "##contig=<ID=chr11,length=135006516,assembly=hg19>",
            "##contig=<ID=chr12,length=133851895,assembly=hg19>",
            "##contig=<ID=chr13,length=115169878,assembly=hg19>",
            "##contig=<ID=chr14,length=107349540,assembly=hg19>",
            "##contig=<ID=chr15,length=102531392,assembly=hg19>",
            "##contig=<ID=chr16,length=90354753,assembly=hg19>",
            "##contig=<ID=chr17,length=81195210,assembly=hg19>",
            "##contig=<ID=chr18,length=78077248,assembly=hg19>",
            "##contig=<ID=chr19,length=59128983,assembly=hg19>",
            "##contig=<ID=chr20,length=63025520,assembly=hg19>",
            "##contig=<ID=chr21,length=48129895,assembly=hg19>",
            "##contig=<ID=chr22,length=51304566,assembly=hg19>",
  ]

params:
  location_variant: "chr3:97510670"

  ignore_centromere: True

  confidence_coefficient: 0.95

  variant_frequency: 2.22E-6

  #Mode en cours de création qui va permettre de lancer un script qui cherchera a optimiser les para plink pour trouver le plus de ROH entre les patients, ce sera plus long par conséquent
  optimisation_mode: False

  ROH_detect_software: "plink"

  dating_software: "Mutation_Age"



