$schema: "https://json-schema.org/draft/2020-12/schema"
description: snakemake configuration file, JSON schema recommandation

type: object

properties:

  samples: 
    type: string

  list_puce_fam: 
    type: string

  ref :
    properties:
      species: 
        type: string

      data_type: 
        type: string

      build: 
        type: string

      contig_lenght: 
        type: array

  params:
    type: object
    properties:
      location_variant: 
        type: string

      confidence_coefficient: 
        type: number

      variant_frequency: 
        type: number

      #Mode en cours de création qui va permettre de lancer un script qui cherchera a optimiser les para plink pour trouver le plus de ROH entre les patients, ce sera plus long par conséquent
      optimisation_mode: 
        type: boolean

      ROH_detect_software: 
        type: string

      dating_software: 
        type: string
    required:
      - location_variant
      - confidence_coefficient
      - optimisation_mode
      - ROH_detect_software
      - dating_software
    

