params:
  Analysis_mode: by_gene
  Data_input: snp
  ROH_detect_software: plink
  confidence_coefficient: 0.95
  correction_dating: 'false'
  dating_software: R_mutation
  ignore_centromere: 'true'
  n_cores: 6
  ram: 35
  variant_frequency: 2.22e-06
path:
  ROH_select: /home1/BAS/hameaue/LIRRA/results/ROH_select.tsv
  config: /home1/BAS/hameaue/LIRRA/config/config.yaml
  custom_track: /home1/BAS/hameaue/LIRRA/results/custom_track.tsv
  data_clean: /home1/BAS/hameaue/LIRRA/results/Full_data_clean.tsv
  envs_R: /home1/BAS/hameaue/LIRRA/workflow/envs/R_env.yml
  excel_output: /home1/BAS/hameaue/LIRRA/results/summary.xlsx
  fasta_genome: /home1/BAS/hameaue/LIRRA/resources/hg19.fa
  final_dating: /home1/BAS/hameaue/LIRRA/results/dating.txt
  full_results: /home1/BAS/hameaue/LIRRA/results/full_results.tsv
  global_summary: /home1/BAS/hameaue/LIRRA/results/global_summary.tsv
  hap-ibd_hbd: /home1/BAS/hameaue/LIRRA/results/hap-ibd.hbd
  hap-ibd_hbd_gz: /home1/BAS/hameaue/LIRRA/results/hap-ibd.hbd.gz
  input_fam: /home1/BAS/hameaue/LIRRA/results/input_puce.fam
  input_map: /home1/BAS/hameaue/LIRRA/results/data_input.map
  list_puce_fam: /home1/BAS/hameaue/LIRRA/config/list_puce_fam.fam
  plink_fam: /home1/BAS/hameaue/LIRRA/results/plink.fam
  plink_hom: /home1/BAS/hameaue/LIRRA/results/plink.hom
  plink_lgen: /home1/BAS/hameaue/LIRRA/results/plink.lgen
  plink_map: /home1/BAS/hameaue/LIRRA/results/plink.map
  plink_zero: /home1/BAS/hameaue/LIRRA/results/plink_with_zero.map
  raw_data: /home1/BAS/hameaue/LIRRA/config/snp_data.tsv
  raw_list: /home1/BAS/hameaue/LIRRA/workflow/schemas/list_puce_fam.schema.yaml
  report: /home1/BAS/hameaue/LIRRA/workflow/report/workflow.rst
  schema_config: /home1/BAS/hameaue/LIRRA/workflow/schemas/config.schema.yaml
  schema_samples: /home1/BAS/hameaue/LIRRA/workflow/schemas/samples.schema.yaml
  vcf_phased: /home1/BAS/hameaue/LIRRA/results/vcf_phased.vcf.gz
  vcf_unphased: /home1/BAS/hameaue/LIRRA/results/vcf_unphased.vcf
puce_informations:
  location_centromeres:
    chr1: 121000000-144000000
    chr10: 39000000-42500000
    chr11: 51000000-56000000
    chr12: 34000000-38000000
    chr13: 16419000-19500000
    chr14: 15500000-19500000
    chr15: 15000000-20500000
    chr16: 34500000-39000000
    chr17: 22000000-26000000
    chr18: 15000000-19500000
    chr19: 24000000-28800000
    chr2: 90000000-96000000
    chr20: 25000000-29500000
    chr21: 10500000-14500000
    chr22: 11500000-16000000
    chr3: 90439303-93641533
    chr4: 49000000-52000000
    chr5: 46000000 -49500000
    chr6: 58500000-62500000
    chr7: 57500000-62500000
    chr8: 42500000-48000000
    chr9: 47000000-65000000
ref:
  build: hg19
  contig_length:
    chr1: '249250621'
    chr10: '135534747'
    chr11: '135006516'
    chr12: '133851895'
    chr13: '115169878'
    chr14: '107349540'
    chr15: '102531392'
    chr16: '90354753'
    chr17: '81195210'
    chr18: '78077248'
    chr19: '59128983'
    chr2: '243199373'
    chr20: '63025520'
    chr21: '48129895'
    chr22: '51304566'
    chr3: '198022430'
    chr4: '191154276'
    chr5: '180915260'
    chr6: '171115067'
    chr7: '159138663'
    chr8: '146364022'
    chr9: '141213431'
  data_type: snp
  species: homo_sapiens
samples: config/snp_data.tsv
variant_informations:
  location_variant: chr4:5800000
